apiVersion: v1
kind: Service
metadata:
  name: mylabel001-service
spec:
  selector:
    app: mylabel_001  #<---
  type: NodePort
  ports:
  - port: 80
    targetPort: 80

# Our service will expose the pod with label app:mylabel_001
# But not on a pod with mylabel_002, which is exposing the same targetPort
