#LimitRanges are specified for individual namespaces

apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint

spec:
  limits:
    - default:          
        cpu: 500m       #<---- the default limit for the namespace
      defaultRequest:
        cpu: 500m       #<---- the default request for the namespace
      max:
        cpu: "1"        #<---- the namespace max limit
      min:
        cpu: 100m       #<---- the namespace min request
      type: Container

---

apiVersion: v1
kind: LimitRange
metadata:
  name: mem-resource-constraint

spec:
  limits:
    - default:
        memory: 256mi   #<---- limit
      defaultRequest:
        memory: 128mi   #<---- request
      max:
        memory: 256mi   #<---- limit
      min:
        memory: 128mi   #<---- request
      type: Container