apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-single
  namespace: dev
  labels:
    name: myapp-pod-single
    type: front-end
spec:
  containers:
  - name: myapp-pod-single
    image: docker.io/library/nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
