apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment
    type: front-end-deployment
spec:
  selector:
    matchLabels:
      app: myapp-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp-deployment
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
