apiVersion: v1
kind: Service
metadata:
  name: cip-example-service

spec:
  selector:
    app: myapp-pod-single
  type: ClusterIP
  ports:
  - name: clusterip-port
    port: 80
    targetPort: 80
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: np-example-service

spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: nodeport-30888
    port: 888
    targetPort: 888
    protocol: TCP
    nodePort: 30888
  - name: nodeport-dynamic
    port: 7070
    targetPort: 7070
    protocol: TCP
    #nodePort: 30777